---
title: "Advanced R course set up pipeline with targets"
author: "Inga Tummoszeit"
format: html
editor: visual
---

## Set up targets

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipodomics <- tar_read(lipidomics)
```

## Making a table

```{r}
lipodomics %>%
  group_by(metabolite) %>%
  summarise(across(value, list(mean = mean, sd = sd))) %>%
  mutate(across(where(is.numeric), \(x) sprintf("%.1f", round(x, digits = 1)))) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, "Mean SD" = MeanSD)
```

## Results: basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset"
  )
```

## Results: basic stats table with gt

```{r}
tar_read(table_descriptive_stats) |>
  gt::gt() |>
  gt::tab_header(
    title = "The mean and standard deviation of metabolites in the lipidomics dataset",
    subtitle = "with gt package"
  )

#   data_color( apply_to = "text", colors='white')
```

## Plot of distributions

```{r}
ggplot(lipodomics, aes(x = value)) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free") + # it is variable and the scale is free (for each histogram)
  theme_minimal()
```

## Results: Distribution plot

```{r}
tar_read(plot_distributions)
```

## Preparing the data

```{r}
lipodomics |>
  count(code, metabolite) |>
  filter(n > 1)
```

```{r}
tar_read(lipidomics)
```

```{r}
lipodomics |>
  filter(metabolite == "Cholesterol") |>
  mutate(
    class = as.factor(class),
    value = scale(value)
  )
```

```{r}
preprocess <- function(data) {
  data |>
    dplyr::mutate(class = as.factor(class), value = scale(value))
}
```

```{r}
just_cholesterol <- lipodomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess()

stats::glm(
  formula = class ~ value,
  data = just_cholesterol, family = binomial
) |>
  broom::tidy(exponentiate = T) |>
  mutate(
    metabolite = unique(just_cholesterol$metabolite),
    model = format(class ~ value),
    .before = everything()
  )
```

```{r}
#' Univariate logistic regression
#'
#' @param data lipidomics data preproccessed for a specific metabolite
#' @param model dependent ~ independent variable (model)
#'
#' @returns a data.frame
fit_model <- function(data, model) {
  stats::glm(model, data, family = binomial) |>
    broom::tidy(exponentiate = T) |>
    dplyr::mutate(
      metabolite = unique(data$metabolite),
      model = format(model),
      .before = tidyr::everything()
    )
}
```

```{r}
lipodomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess() |>
  fit_model(class ~ value)
```

## Running multiple models

```{r}
just_cholesterol <- lipodomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess()

lipodomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess() |>
  fit_all_models()
```

## For all metabolites

```{r}
lipodomics |>
  group_split(metabolite) |>
  purrr::map(\(data) preprocess(data) |>
    fit_all_models()) |>
  purrr::list_rbind()
```

```{r}
lipodomics |>
  group_split(metabolite) |>
  purrr::map(preprocess) |>
  purrr::map(fit_all_models) |>
  purrr::list_rbind()
```

## Appendix

```{r}
tar_read(glm_model_results) |>
  gt::gt() |>
  gt::tab_header(
    title = "Results of the glm with and without confounders for all metabolites",
    subtitle = "with gt package"
  )
```
